name: cuidapet_api
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.2.5

dependencies:
  args: ^2.5.0
  get_it: ^7.7.0
  http: ^1.2.0
  injectable: ^2.4.2
  jaguar_jwt: ^3.0.0
  logger: ^2.3.0
  mysql1: ^0.20.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  dotenv: ^4.2.0

dev_dependencies:
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  lints: ^2.1.0
  pedantic: ^1.9.0
  shelf_router_generator: ^1.1.0
  test: ^1.24.0
